mex Bspline.cpp Bspline_wrapper.cpp ...
    -IC:\Users\DurandauGV\Documents\CEINMS\CEINMS-RT\trunk\lib\MTUSpline ...
    -IC:\Users\DurandauGV\Documents\CEINMS\CEINMS-RT\trunk\lib\NMSmodel ...
    -IC:\Users\DurandauGV\Documents\CEINMS\CEINMS-RT\trunk\lib\Curve ...
    -IC:\Users\DurandauGV\Documents\CEINMS\CEINMS-RT\trunk\lib\ModelEvaluation ...
-IC:\Users\DurandauGV\Documents\CEINMS\CEINMS-RT\trunk\lib\FileIO ...
-IC:\Users\DurandauGV\Documents\CEINMS\CEINMS-RT\trunk\lib\OdeInt ...
-IC:\Users\DurandauGV\Documents\CEINMS\CEINMS-RT\trunk\lib\xmlInput ...
-IC:\Users\DurandauGV\Documents\CEINMS\CEINMS-RT\trunk\src ...
-I"C:\Program Files (x86)\CodeSynthesis XSD 4.0\include" ...
-IC:\local\boost_1_64_0 ...
-LC:\Users\DurandauGV\Documents\CEINMS\CEINMS-RT\trunk\bin\Win\Release ...
-LC:\local\boost_1_64_0 ...
-LC:\local\boost_1_64_0\lib64-msvc-12.0 ...
-lMTUSpline.lib ...
-lNMSmodel.lib ...
-lxmlInput.lib ...
-L"C:\Program Files (x86)\CodeSynthesis XSD 4.0\lib64\vc-12.0" ...
-lxerces-c_3.lib
%-lC:\local\boost_1_64_0\lib64-msvc-12.0\libboost_timer-vc120-mt-1_64.lib ...