FROM ubuntu:24.04

RUN apt-get update && \
    apt-get install -y \
        git \
        python-is-python3 \
        python3-pip \
        python3-venv \
        cmake&& \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

CMD ["/bin/bash"]